// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { Application } from '@hotwired/stimulus'
import NestedForm from 'stimulus-rails-nested-form'
import Chart from 'stimulus-chartjs'

const application = Application.start()
application.register('nested-form', NestedForm)
application.register('chart', Chart)

// import AddressesController from "./addresses_controller"
// application.register("addresses", AddressesController)

// import BalanceController from "./balance_controller"
// application.register("balance", BalanceController)

// import PortfoliosController from "./portfolios_controller"
// application.register("portfolios", PortfoliosController)
