// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BalanceController from "./balance_controller"
application.register("balance", BalanceController)

import ChartsController from "./charts_controller"
application.register("charts", ChartsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import TransactionsController from "./transactions_controller"
application.register("transactions", TransactionsController)

